
import { ItemConfig, StockItemConfig } from './types';

export const INITIAL_ITEMS: ItemConfig[] = [
  { id: '1', name: 'Lemonade', nameBN: 'লেমনেড', price250: 60, price350: 80, color: '#f7fee7', icon: '🍋' },
  { id: '2', name: 'Lacchi', nameBN: 'লাচ্ছি', price250: 70, price350: 100, color: '#fffbeb', icon: '🥛' },
  { id: '3', name: 'Cold Coffee', nameBN: 'কোল্ড কফি', price250: 90, price350: 120, color: '#fef3c7', icon: '☕' },
  { id: '4', name: 'Oreo Milk', nameBN: 'ওরিও মিল্ক', price250: 100, price350: 130, color: '#f3f4f6', icon: '🍪' },
  { id: '5', name: 'Chocolate Milk', nameBN: 'চকলেট মিল্ক', price250: 110, price350: 150, color: '#fff7ed', icon: '🍫' },
  { id: '6', name: 'Chocolate Coffee', nameBN: 'চকলেট কফি', price250: 120, price350: 160, color: '#fafaf9', icon: '🥤' },
  { id: '7', name: 'Kitkat Milk', nameBN: 'কিটকাট মিল্ক', price250: 130, price350: 170, color: '#fef2f2', icon: '🍫' },
  { id: '8', name: 'Green Mango', nameBN: 'কাঁচা আম', price250: 70, price350: 100, color: '#f0fdf4', icon: '🍏' },
  { id: '9', name: 'Mango', nameBN: 'আম', price250: 100, price350: 140, color: '#fff7ed', icon: '🥭' },
  { id: '10', name: 'Papaya', nameBN: 'পেঁপে', price250: 100, price350: 130, color: '#fff7ed', icon: '🍈' },
  { id: '11', name: 'Watermelon', nameBN: 'তরমুজ', price250: 100, price350: 140, color: '#fff1f2', icon: '🍉' },
  { id: '12', name: 'Date Smoothie', nameBN: 'খেজুর', price250: 100, price350: 130, color: '#fafaf9', icon: '🌴' },
  { id: '13', name: 'Malta', nameBN: 'মাল্টা', price250: 100, price350: 140, color: '#fff7ed', icon: '🍊' },
  { id: '14', name: 'Orange', nameBN: 'কমলা', price250: 100, price350: 140, color: '#fff7ed', icon: '🍊' },
  { id: '15', name: 'Pineapple', nameBN: 'আনারস', price250: 100, price350: 130, color: '#fefce8', icon: '🍍' },
  { id: '16', name: 'Blueberry', nameBN: 'ব্লুবেরি', price250: 150, price350: 200, color: '#eff6ff', icon: '🫐' },
  { id: '17', name: 'Mulberry', nameBN: 'মালবেরি', price250: 150, price350: 200, color: '#fdf4ff', icon: '🍇' },
  { id: '18', name: 'Strawberry', nameBN: 'স্ট্রবেরি', price250: 150, price350: 200, color: '#fff1f2', icon: '🍓' },
  { id: '19', name: 'Kiwi', nameBN: 'কিউই', price250: 150, price350: 200, color: '#f0fdf4', icon: '🥝' },
  { id: '20', name: 'Passion Fruit', nameBN: 'প্যাশন', price250: 150, price350: 200, color: '#fffbeb', icon: '🍇' },
  { id: '21', name: 'Boba', nameBN: 'বোবা', price250: 20, price350: 20, color: '#f3f4f6', icon: '🧋' },
];

export const STOCK_ITEMS: StockItemConfig[] = [
  { id: 's1', name: 'Sugar', nameBN: 'চিনি' },
  { id: 's2', name: 'Hersleys Strawberry', nameBN: 'হার্শিস স্ট্রবেরি' },
  { id: 's3', name: 'Hersleys Chocolate', nameBN: 'হার্শিস চকলেট' },
  { id: 's4', name: 'Hersleys Caramel', nameBN: 'হার্শিস ক্যারামেল' },
  { id: 's5', name: 'Milk (Liquid)', nameBN: 'তরল দুধ' },
  { id: 's6', name: 'Milk (Powder)', nameBN: 'গুঁড়া দুধ' },
  { id: 's7', name: 'Yogurt', nameBN: 'দই' },
  { id: 's8', name: 'Lemon', nameBN: 'লেবু' },
  { id: 's9', name: 'Pudina', nameBN: 'পুদিনা' },
  { id: 's10', name: 'Bit solt', nameBN: 'বিট লবণ' },
  { id: 's11', name: 'Cadbury powder', nameBN: 'ক্যাডবেরি পাউডার' },
  { id: 's12', name: 'Choco chips', nameBN: 'চকো চিপস' },
  { id: 's13', name: 'Coffee', nameBN: 'কফি' },
  { id: 's14', name: 'Oreo', nameBN: 'ওরিও' },
  { id: 's15', name: 'Kitkat', nameBN: 'কিটকাট' },
  { id: 's16', name: 'Coconut jelly', nameBN: 'নারকেল জেলি' },
  { id: 's17', name: 'Boba Pearl', nameBN: 'বোবা পার্ল' },
  { id: 's18', name: 'Blueberry', nameBN: 'ব্লুবেরি' },
  { id: 's19', name: 'Murlberry', nameBN: 'মালবেরি' },
  { id: 's20', name: 'Strawberry', nameBN: 'স্ট্রবেরি' },
  { id: 's21', name: 'Kiwi', nameBN: 'কিউই' },
  { id: 's22', name: 'Passion', nameBN: 'প্যাশন' },
  { id: 's23', name: 'PVC Glass', nameBN: 'পিভিসি গ্লাস' },
  { id: 's24', name: 'Pipe', nameBN: 'পাইপ' },
  { id: 's25', name: 'Role', nameBN: 'রোল' },
  { id: 's26', name: 'Mango', nameBN: 'আম' },
  { id: 's27', name: 'Green Mango', nameBN: 'কাঁচা আম' },
  { id: 's28', name: 'Papaya', nameBN: 'পেঁপে' },
  { id: 's29', name: 'Watermelon', nameBN: 'তরমুজ' },
  { id: 's30', name: 'Date', nameBN: 'খেজুর' },
  { id: 's31', name: 'Malta', nameBN: 'মাল্টা' },
  { id: 's32', name: 'Orange', nameBN: 'কমলা' },
  { id: 's33', name: 'Pineapple', nameBN: 'আনারস' },
];

export const TRANSLATIONS = {
  EN: {
    title: 'SMOOTHIE BAR',
    itemHeader: 'Product',
    q250: '250ml',
    q350: '350ml',
    total: 'Total',
    totalSales: 'Total Sales',
    purchase: 'Purchase',
    expense: 'Expenses',
    cashInHand: 'Cash in Hand',
    previousBalance: 'Previous Balance',
    totalBalance: 'Total Balance',
    notes: 'Notes / Remarks',
    share: 'SHARE',
    settings: 'Settings',
    save: 'Save Changes',
    editPrice: 'Manage Products',
    languageLabel: 'Language',
    langBtn: 'Switch to বাংলা',
    taka: '৳',
    shareVia: 'Share via...',
    backup: 'Backup',
    downloadBackup: 'Export Data',
    uploadBackup: 'Import Data',
    importSuccess: 'Data imported successfully!',
    importError: 'Failed to import data.',
    viewMode: 'View Mode',
    dailySales: 'Daily Sales',
    monthlyStock: 'Monthly Stock',
    qty: 'QTY',
    rate: 'Taka',
    grandTotal: 'Grand Total',
    shareSalesTitle: 'Share Sales Summary',
    shareStockTitle: 'Share Stock Summary',
    securityPin: 'Security PIN',
    cloudSync: 'Cloud Synchronization',
    manageProducts: 'Manage Products',
    enterPin: 'Enter Security PIN',
    incorrectPin: 'Incorrect PIN. Try again.',
    unlockToEdit: 'Unlock to Edit',
    lockedMsg: 'History is locked. Use PIN to edit.',
    unlockedMsg: 'Data is now editable.',
    synced: 'Synced to Cloud',
    syncing: 'Syncing to Cloud...',
    changePin: 'Change PIN',
    oldPin: 'Current PIN',
    newPin: 'New PIN',
    confirmPin: 'Confirm PIN',
    pinMismatch: 'New PINs do not match.',
    pinSuccess: 'PIN changed successfully!',
    messenger: 'Messenger',
    copyText: 'Copy Text',
  },
  BN: {
    title: 'স্মুদি বার',
    itemHeader: 'আইটেম',
    q250: '২৫০ মি.লি.',
    q350: '৩৫০ মি.লি.',
    total: 'মোট',
    totalSales: 'মোট বিক্রয়',
    purchase: 'ক্রয়',
    expense: 'খরচ',
    cashInHand: 'ক্যাশ ইন হ্যান্ড',
    previousBalance: 'আগের ব্যালেন্স',
    totalBalance: 'মোট ব্যালেন্স',
    notes: 'নোট / মন্তব্য',
    share: 'SHARE',
    settings: 'সেটিংস',
    save: 'সেভ করুন',
    editPrice: 'আইটেম ম্যানেজমেন্ট',
    languageLabel: 'ভাষা',
    langBtn: 'Switch to English',
    taka: '৳',
    shareVia: 'শেয়ার করুন...',
    backup: 'ব্যাকআপ',
    downloadBackup: 'ডাউনলোড',
    uploadBackup: 'আপলোড',
    importSuccess: 'সফলভাবে ইমপোর্ট হয়েছে!',
    importError: 'ইমপোর্ট ব্যর্থ হয়েছে।',
    viewMode: 'ভিউ মোড',
    dailySales: 'দৈনিক বিক্রয়',
    monthlyStock: 'মাসিক স্টক',
    qty: 'QTY',
    rate: 'টাকা',
    grandTotal: 'সর্বমোট',
    shareSalesTitle: 'বিক্রয় রিপোর্ট শেয়ার',
    shareStockTitle: 'স্টক রিপোর্ট শেয়ার',
    securityPin: 'সিকিউরিটি পিন',
    cloudSync: 'ক্লাউড সিনক্রোনাইজেশন',
    manageProducts: 'প্রোডাক্ট ম্যানেজমেন্ট',
    enterPin: 'সিকিউরিটি পিন দিন',
    incorrectPin: 'ভুল পিন। আবার চেষ্টা করুন।',
    unlockToEdit: 'এডিট করতে আনলক করুন',
    lockedMsg: 'ইতিহাস লক করা আছে। এডিট করতে পিন ব্যবহার করুন।',
    unlockedMsg: 'এখন ডাটা এডিট করা যাবে।',
    synced: 'ক্লাউডে সেভ হয়েছে',
    syncing: 'ক্লাউডে সেভ হচ্ছে...',
    changePin: 'পিন পরিবর্তন',
    oldPin: 'পুরানো পিন',
    newPin: 'নতুন পিন',
    confirmPin: 'পিন নিশ্চিত করুন',
    pinMismatch: 'নতুন পিন মিলছে না।',
    pinSuccess: 'পিন সফলভাবে পরিবর্তিত হয়েছে!',
    messenger: 'মেসেঞ্জার',
    copyText: 'টেক্সট কপি',
  }
};
