import { ItemConfig } from './types';

export const INITIAL_ITEMS: ItemConfig[] = [
  { id: '1', name: 'Lemonade', nameBN: 'লেমনেড', price250: 60, price350: 80 },
  { id: '2', name: 'Green Mango', nameBN: 'কাঁচা আম', price250: 70, price350: 100 },
  { id: '3', name: 'Lacchi', nameBN: 'লাচ্ছি', price250: 70, price350: 100 },
  { id: '4', name: 'Pineapple', nameBN: 'আনারস', price250: 100, price350: 130 },
  { id: '5', name: 'Cold Coffee', nameBN: 'কোল্ড কফি', price250: 90, price350: 120 },
  { id: '6', name: 'Chocolate Coffee', nameBN: 'চকলেট কফি', price250: 120, price350: 160 },
  { id: '7', name: 'Oreo Milk', nameBN: 'ওরিও মিল্ক', price250: 100, price350: 130 },
  { id: '8', name: 'Chocolate Milk', nameBN: 'চকলেট মিল্ক', price250: 110, price350: 150 },
  { id: '9', name: 'Kitkat Milk', nameBN: 'কিটকাট মিল্ক', price250: 130, price350: 170 },
  { id: '10', name: 'Mango', nameBN: 'আম', price250: 100, price350: 140 },
  { id: '11', name: 'Papaya', nameBN: 'পেঁপে', price250: 100, price350: 130 },
  { id: '12', name: 'Watermelon', nameBN: 'তরমুজ', price250: 100, price350: 140 },
  { id: '13', name: 'Date', nameBN: 'খেজুর', price250: 100, price350: 130 },
  { id: '14', name: 'Malta', nameBN: 'মাল্টা', price250: 100, price350: 140 },
  { id: '15', name: 'Orange', nameBN: 'কমলা', price250: 100, price350: 140 },
  { id: '16', name: 'Blueberry', nameBN: 'ব্লুবেরি', price250: 150, price350: 200 },
  { id: '17', name: 'Mulberry', nameBN: 'মালবেরি', price250: 150, price350: 200 },
  { id: '18', name: 'Strawberry', nameBN: 'স্ট্রবেরি', price250: 150, price350: 200 },
  { id: '19', name: 'Kiwi', nameBN: 'কিউই', price250: 150, price350: 200 },
  { id: '20', name: 'Passion', nameBN: 'প্যাশন', price250: 150, price350: 200 },
  { id: '21', name: 'Boba', nameBN: 'বোবা', price250: 20, price350: 20 },
];

export const TRANSLATIONS = {
  EN: {
    title: 'SMOOTHIE BAR',
    itemHeader: 'Product',
    q250: '250ml',
    q350: '350ml',
    total: 'Total',
    totalSales: 'Total Sales',
    purchase: 'Purchase',
    expense: 'Expenses',
    cashInHand: 'Cash in Hand',
    previousBalance: 'Previous Balance',
    totalBalance: 'Total Balance',
    notes: 'Notes / Remarks',
    share: 'SHARE',
    settings: 'Settings',
    save: 'Save Changes',
    editPrice: 'Manage Products',
    languageLabel: 'Language',
    langBtn: 'Switch to বাংলা',
    taka: '৳',
    shareVia: 'Share via...',
    backup: 'Backup',
    downloadBackup: 'Export Data',
    uploadBackup: 'Import Data',
    importSuccess: 'Data imported successfully!',
    importError: 'Failed to import data.',
    clearAll: 'Clear all',
  },
  BN: {
    title: 'স্মুদি বার',
    itemHeader: 'আইটেম',
    q250: '২৫০ মি.লি.',
    q350: '৩৫০ মি.লি.',
    total: 'মোট',
    totalSales: 'মোট বিক্রয়',
    purchase: 'ক্রয়',
    expense: 'খরচ',
    cashInHand: 'ক্যাশ ইন হ্যান্ড',
    previousBalance: 'আগের ব্যালেন্স',
    totalBalance: 'মোট ব্যালেন্স',
    notes: 'নোট / মন্তব্য',
    share: 'SHARE',
    settings: 'সেটিংস',
    save: 'সেভ করুন',
    editPrice: 'আইটেম ম্যানেজমেন্ট',
    languageLabel: 'ভাষা',
    langBtn: 'Switch to English',
    taka: '৳',
    shareVia: 'শেয়ার করুন...',
    backup: 'ব্যাকআপ',
    downloadBackup: 'ডাউনলোড',
    uploadBackup: 'আপলোড',
    importSuccess: 'সফলভাবে ইমপোর্ট হয়েছে!',
    importError: 'ইমপোর্ট ব্যর্থ হয়েছে।',
    clearAll: 'সব মুছুন',
  }
};